### ISSUE TITLE
WebDAV: Add Bearer authentication support e.g. for ownCloud 10

### ISSUE THREAD

**Issue by dorianim** [photoprism/photoprism#2267]
**What does not work as described in the documentation?**

I tried setting up syncing with Owncloud as described here: https://docs.photoprism.app/user-guide/settings/sync/

However, when I try to set up the sync, I always get the error `Could not connect, please try again` and in the logs: `level=error msg="account-folder: Authorize https://owncloud.example.com/remote.php/dav/files/photoprism-binduser/: 401`

I tried the same parameters in Nautilus, and it works fine, so I assume that the problem is not with Owncloud.

**How can we reproduce it?**

1. Go to 'Settings > Sync'
2. Click on 'ADD SERVER'
3. Enter valid parameters for an Owncloud WebDAV endpoint
4. Click on the sync icon to configure syncing
5. The error from above appears and the Folder dropdown is empty

**What behavior do you expect?**

No error and a list of available folders in the Folder dropdown.

**What could be the cause of your problem?**

Maybe an issue with the WebDAV lib in Photoprism or a wrong URL.

**Can you provide us with example files for testing, error logs, or screenshots?**

- Log in Photoprism: `level=error msg="account-folder: Authorize https://cloud.itsblue.de/remote.php/dav/files/photoprism-binduser/: 401`
- Log in Owncloud: `"PROPFIND /remote.php/dav/files/photoprism-binduser/
HTTP/1.1" 401 1668 "-" "Go-http-client/2.0"`

**Which software versions do you use?**

- PhotoPrism Build 220302-0059f429-Linux-AMD64
- MariaDB 10.5
- OwnCloud 10.9.1 (stable) 

**Do you use a Reverse Proxy, Firewall, VPN, or CDN?**

- Yes Traefik for both, Owncloud and Photoprism

**Comment by lastzero** [comment]
- Does it work when you enter the protocol and hostname only, without path?
 - Does the server have a valid HTTPS certificate? 
 - Any specific auth requirements / settings in ownCloud? Should basic auth work? 
 - Does it work with our preview build?

**Comment by dorianim** [comment]
Thanks for the reply!

> Does it work when you enter the protocol and hostname only, without path?

Nope, the error changes: `account-folder: ReadDir /: 405 Method Not Allowed - PROPFIND /`

> Does the server have a valid HTTPS certificate?

Yes

> Any specific auth requirements / settings in ownCloud? Should basic auth work?

I don't think so. It's basically a vanilla Owncloud with a normal account. Auth works in Nautilus.

> Does it work with our preview build?

Nope, same error as above

**Comment by faquad** [comment]
The error with http `PROFIND` comes either from the owncloud itself or from the owncloud's reverse-proxy (nginx or apache) - the server seems to block this http method. 
Nautilus seems to be able to handle the case where `PROFIND` is not supported.

**Comment by dorianim** [comment]
The error appears, because the path `/` is not valid for PROFIND. Only `/remote.php/dav/files/photoprism-binduser/` allows it.

I think, this is to be expected and not related to the issue.

**Comment by faquad** [comment]
ah, agree, i guess it must be fixed on the go-http-client side to use  `/remote.php/dav/files/photoprism-binduser/` instead of `/`

**Comment by lastzero** [comment]
Definitely an authentication / http configuration issue. Found many similar reports related to WebDAV and Owncloud via Google:

- https://github.com/owncloud/core/issues/12146
- https://github.com/owncloud/core/issues/21461

The auto detected WebDAV resource URL is OK (no such thing and "-binduser" etc, this is the exact same URL that Owncloud provides in their UI for connecting with the admin user):

```
https://owncloud.photoprism.dev/remote.php/dav/files/admin/
```

However, authentication fails with code 401. So it COULD be related to:
- MOD_X_ACCEL_REDIRECT_ENABLED
- mod_rewrite
- Sabre_DAV
- fastcgi
- ...

If I had a second to test more, I would, but that is not possible. A good opportunity to contribute and find out what's wrong!

As it looks to me, WebDAV will probably work with Owncloud OCIS and/or other Ownload 10 settings :+1:

**Comment by tarun-menta** [comment]
I'd like to try working on this, could this be assigned to me?

**Comment by lastzero** [comment]
I'm working on WebDAV right now anyway, so if you could figure out what is causing this and needs to be changed so we can take care of it, that would be a big help already!

**Comment by tarun-menta** [comment]
Is there a HTTPS OwnCloud dev server setup that I can use to test?

**Comment by lastzero** [comment]
This is the docker-compose.yml that we use for testing. Of course, you need Traefik with Let's Encrypt (DNS challenge for wildcard certificates), MariaDB and Redis to make it work as shown here. You also need to adjust the network configuration and domains to your environment (see our [development environment](https://github.com/photoprism/photoprism/blob/develop/docker-compose.yml) for how to use this together):

```yaml
version: '3.5'

networks:
  default:
    name: backend
    external: true

services:
  owncloud:
    container_name: "owncloud-10"
    image: owncloud/server:10
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.owncloud.entrypoints=websecure"
      - "traefik.http.middlewares.secure.headers.stsSeconds=15552000"
      - "traefik.http.routers.owncloud.middlewares=secure"
      - "traefik.http.routers.owncloud.tls.domains[0].main=yourdomain.dev"
      - "traefik.http.routers.owncloud.tls.domains[0].sans=*.yourdomain.dev"
      - "traefik.http.routers.owncloud.tls.certresolver=myresolver"
      - "traefik.http.routers.owncloud.rule=Host(`owncloud.yourdomain.dev`)"
      - "traefik.http.routers.owncloud.tls=true"
    environment:
      OWNCLOUD_DOMAIN: "owncloud.yourdomain.dev"
      OWNCLOUD_DB_TYPE: "mysql"
      OWNCLOUD_DB_NAME: "owncloud_10"
      OWNCLOUD_DB_USERNAME: "owncloud_10"
      OWNCLOUD_DB_PASSWORD: "owncloud_10"
      OWNCLOUD_DB_HOST: "mariadb"
      OWNCLOUD_ADMIN_USERNAME: "admin"
      OWNCLOUD_ADMIN_PASSWORD: "photoprism"
      OWNCLOUD_MYSQL_UTF8MB4: "true"
      OWNCLOUD_REDIS_ENABLED: "true"
      OWNCLOUD_REDIS_HOST: "redis"
    volumes:
      - "./data:/mnt/data/"
```

**Comment by tarun-menta** [comment]
The issue is with how the `gowebdav` package handles authentication. It is currently only setup to handle three types of Auth: `Basic`, `Digest`, and NoAuth. The type of authentication is chosen by checking the `Www-Authenticate` header returned by the WebDAV Server. 

However, OwnCloud requires a `Bearer` type authentication, which is not supported by the `gowebdav` package, and it simply omits the authorization header, causing the `401` status code. Should be a pretty simple fix on the package.

Snippet of the authentication code from the `gowebdav` package
```go
if strings.Index(wwwAuthenticateHeader, "digest") > -1 {
  c.authMutex.Lock()
  c.auth = &DigestAuth{auth.User(), auth.Pass(), digestParts(rs)}
  c.authMutex.Unlock()
} else if strings.Index(wwwAuthenticateHeader, "basic") > -1 {
  c.authMutex.Lock()
  c.auth = &BasicAuth{auth.User(), auth.Pass()}
  c.authMutex.Unlock()
} else {
  return rs, newPathError("Authorize", c.root, rs.StatusCode)
}
```

**Comment by tarun-menta** [comment]
On digging deeper, a few more observations

Though OwnCloud requires a `Bearer` type authentication and sets the `Www-Authenticate` header accordingly, it also accepts the `basic` auth scheme. `gowebdav` uses NoAuth by default, but by switching this to `Basic` by default, the 401 authorization error is fixed. Additionally, when setting the auth header using a bearer token, the server raises a `Missing basic authorization` error. This seems to be a case of the OwnCloud server setting an incorrect value for the `Www-Authenticate` header. If this header was set correctly by OwnCloud, the 401 authorization error would not occur. 

EDIT: This part of this comment (Regarding improper handling of the `207` status code seems to be an issue with a very recent commit to `gowebdav`, which they are in the process of reverting)
Fixing this reveals another issue with `gowebdav`. With the correct auth as mentioned above, the `PROPFIND` request returns a response with a `207` status code, which `gowebdav` incorrectly treats as an error and discards the output. The output contains the necessary folder details, and parsing it would return the required info (Which is what `gowebdav` should do, instead of treating `207` as an error) 
```go
if rs.StatusCode != 207 {
  return newPathError("PROPFIND", path, rs.StatusCode)
}
```


Seems to be an issue with both OwnCloud and `gowebdav`. Not sure how exactly both can be fixed

**Comment by lastzero** [comment]
We are considering replacing `gowebdav` as it doesn't seem to be properly maintained (anymore). Any stable alternative is fine.

**Comment by tarun-menta** [comment]
Yeah, that makes sense. A temporary fix for the OwnCloud issue would be to set `gowebdav` to default to `Basic` auth, instead of NoAuth. This is still a case of OwnCloud setting an incorrect `Www-Authenticate` header, imo

**Comment by lastzero** [comment]
I just updated the WebDAV client library we use. Unfortunately, it is still not possible to upload to ownCloud 10.

However, in the ownCloud config I found the variable `OWNCLOUD_TOKEN_AUTH_ENFORCED`. Changing this variable did not help, but maybe I just changed it in the wrong place or there are other config options which enable digest or simple auth on their WebDAV API?

**Comment by lastzero** [comment]
@dorianim @peppermenta We have replaced the `studio-b12/gowebdav` client with `emersion/go-webdav` today in an attempt to fix this issue:

- #3310

Since `emersion/go-webdav` uses the regular Go HTTP client, it should also be possible to set request headers for authentication methods other than basic auth. Unfortunately I don't have time to try this right now.

**Comment by lastzero** [comment]
@graciousgrey The switch to `emersion/go-webdav` likely improved compatibility for servers that accept preemptive Basic auth, so some ownCloud setups may now work. However, explicit `Bearer` auth support is still not implemented.
