### ISSUE TITLE
People: Select a photo to use for a person's face

### ISSUE THREAD

**Issue by tetra-archos** [photoprism/photoprism#4151]
**Describe what problem this solves and why this would be valuable to many users**

Ability to select photo used in People for a person's face can keep it from using Private photos (which may be nsfw) as the display photo for a person. Currently even if you mark a photo as private it can be used as the display photo for a person if it was already set that way, even if the photo no longer appears in the People tab

**Describe the solution you'd like**

Set a specific photo for a person

**Describe alternatives you've considered**

I don't see another solution besides hiding a person

**Additional context**

**Comment by graciousgrey** [comment]
> Currently even if you mark a photo as private it can be used as the display photo for a person if it was already set that way, even if the photo no longer appears in the People tab

Thank you for reporting. This should be fixed with #4238

**Comment by Pamalosebi** [comment]
After this FR was closed -> https://github.com/photoprism/photoprism/issues/383

Please consider adding the "Set as Album Cover" for "People" too. Right now its only applied on "Albums".

Thank you!

**Comment by dmedi011** [comment]
would like this as well!

**Comment by lastzero** [comment]
I'm happy to report that you can now test this using our preview build:
- https://docs.photoprism.app/release-notes/#development-preview
- https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by sewebster87** [comment]
Is there documentation to enable this feature?  So far, I have:
- Made sure I am on preview build: PhotoPrism® Plus Build [251102-bbee0993e]
- Enabled Experimental Features
- Re-indexed my entire photo collection
- Made sure my Originals directory is read-write and not read-only

I still can't find where to select the photo to be used on the People page for any given person.  I've tried doing it from the main People page, after clicking on any person and selecting a photo and looking at the batch options (even though I know that doesn't make sense, just trying what I can think of), and then on any individual photo and looking at the options in the 3-dots menu and I just can't find it.  I am probably doing something wrong. 

Happy to provide as many details and logs as I can, sorry if this is not enough information to investigate.

**Comment by graciousgrey** [comment]
@sewebster87 I am happy to help. You can find it as option of a 3-dot menu on the face crops that are shown on the people tab of the edit dialog. We will add more information regarding this to our user guide with the next release.

**Comment by sewebster87** [comment]
@graciousgrey That worked!!!! It's there! Thank you!!!

For others, the specific workflow is:
1. Click People on the left
2. Select a person
3. Find and click on the photo you want to use for Cover Image 
4. Click the Edit pencil icon 
5. Go to the People tab
6. Click the 3-dots menu on the face of the user you picked in Step 2 (all other "people" should have only an X, whereas the person you selected in Step 2 will have the 3-dots menu)
7. Click Set as Cover Image

PhotoPrism has the right permissions to allow my large family with thousands of photos to view and browse by People with decent pictures, see Folders w/ folder names, and each of the users gets their own login.  Thanks for getting back to me so quickly, you rock.
