### ISSUE TITLE
GPS location not correctly imported

### ISSUE THREAD

**Issue by reneraab** [photoprism/photoprism#431]
Hello,

The current latest version of photoprism (200729-65c57f5-Linux-x86_64) fails to correctly import the GPS coordinates of many of my images. Other tools (e.g. exiftool) correctly extract this information.

I have tried setting `PHOTOPRISM_SIDECAR_JSON` to `true` as suggested in #302, but this did not solve the issue. I have attached one of the problematic pictures to this issue.

This is the output when importing the image:
```
photoprism_1     | time="2020-07-29T15:22:05Z" level=debug msg="exif: interface conversion: interface {} is []exifcommon.Rational, not []uint8 in IMG_20161216_154531.jpg (gps info)"
photoprism_1     | time="2020-07-29T15:22:05Z" level=info msg="metadata: failed parsing gps coordinates in IMG_20161216_154531.jpg (exif)"
```

![IMG_20161216_154531](https://user-images.githubusercontent.com/1470363/88819425-43d24080-d1c0-11ea-9663-c3fcf84c1abe.jpg)

Please let me know whether you need any more information.

Kind regards,
René

**Comment by lastzero** [comment]
@dsoprea Is this something that needs to be fixed in go-exif? On vacation right now, so I can't properly debug it.

**Comment by dsoprea** [comment]
Looks like PP is mis-casting the value that's coming back. I should be able to throw together a PR against PP later tonight.

**Comment by lastzero** [comment]
Log points to an error returned by `go-exif`. As mentioned, can't debug it properly right now. Thankful for any pull request or advice!

**Comment by dsoprea** [comment]
Another example of multiple instances of the same tag with different types. Now, we will just skip tags with types that don't agree with the standard. This should fix most of the instances that we see.

Fixed via https://github.com/photoprism/photoprism/pull/434 .

**Comment by dsoprea** [comment]
@reneraab Please confirm that it's fixed.

**Comment by reneraab** [comment]
It works! Thank you :+1:

**Comment by dsoprea** [comment]
Glad to hear it :) .

**Comment by lastzero** [comment]
@dsoprea While this specific image seems to work, many of our tests are failing now - especially one file modified with Photoshop, which was working perfectly before. Date, Location, Lens,... everything gone 😢

Any idea why that is? Exiftool still shows the correct values.

See 
* https://github.com/photoprism/photoprism/commit/7c1886328744938b2805663b84dba250859978e1#diff-625234f75417063e3641fa9510284563
* https://github.com/photoprism/photoprism/commit/b232d374adb870627331867724a325e0c880aee5#diff-3350a5249d6a1e2aa1e7839cac15092d

**Comment by dsoprea** [comment]
Not sure. It was a solid that account for a certain image glitch, and it didn't break any unit-tests (including tests against my own images) .

Can you provide a couple of images?

**Comment by lastzero** [comment]
Failed tests:
- https://travis-ci.org/github/photoprism/photoprism/builds/713607533#L2036
- https://travis-ci.org/github/photoprism/photoprism/builds/713607533#L1343

Those are the image files (see referenced commits / unit tests for details):

https://github.com/photoprism/photoprism/blob/develop/internal/meta/testdata/photoshop.jpg

![](https://github.com/photoprism/photoprism/raw/develop/internal/meta/testdata/photoshop.jpg)

https://github.com/photoprism/photoprism/raw/develop/assets/examples/cat_brown.jpg

![](https://github.com/photoprism/photoprism/raw/develop/assets/examples/cat_brown.jpg)

**Comment by dsoprea** [comment]
I'll look at this in a few minutes.

**Comment by dsoprea** [comment]
It's not specific to GPS locations. The process is crashing because of unknown tags in those images. The last change that I pushed (https://github.com/dsoprea/go-exif/commit/74a1612f20425914ea5ad75ab03b0bac350a094c#diff-5965bde93fe619b40111a6fb9b6a2f28R249) required that we lookup our type-information for our tags so that we can skip any that deviate from the standard so we don't run into undefined scenarios. However, that then fails if those tags aren't known and I wasn't handling that. Fixed in https://github.com/dsoprea/go-exif/commit/089aa48c91e6c40383764367ec933a4b0ca020c7.

**Comment by dsoprea** [comment]
Keep in mind that you should pull updates to go-jpeg/png/tiff, too, as those are very important to you.

**Comment by dsoprea** [comment]
Confirmed as good?

**Comment by lastzero** [comment]
Yes, looks good to me :) All tests green!
